---
- name: Setup web server and database
  hosts: all
  become: yes
  vars:
    db_name: sampledb
    db_user: dbuser
    db_password: dbpassword
  tasks:
    - name: Install necessary packages
      apt:
        name:
          - apache2
          - mysql-server
          - php
          - libapache2-mod-php
          - php-mysql
        state: present
        update_cache: yes

    - name: Start and enable Apache service
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Start and enable MySQL service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Create MySQL database
      mysql_db:
        name: "{{ db_name }}"
        state: present

    - name: Create MySQL user
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: "{{ db_name }}.*:ALL"
        state: present

    - name: Create a sample index.php file
      copy:
        content: |
          <?php
          $conn = new mysqli("localhost", "{{ db_user }}", "{{ db_password }}", "{{ db_name }}");
          if ($conn->connect_error) {
              die("Connection failed: " . $conn->connect_error);
          }
          echo "Connected successfully";
          $sql = "CREATE TABLE IF NOT EXISTS test (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) NOT NULL)";
          $conn->query($sql);
          $conn->close();
          echo "<br>Database setup completed!";
          ?>
        dest: /var/www/html/index.php
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Restart Apache to apply changes
      service:
        name: apache2
        state: restarted
